# .github/workflows/soapranos-potts-scraper.yml
name: soapranos-scraper-all

on:
  workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: scrape-soapranos
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # give apt/browsers a little breathing room
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install "playwright==1.45.0" "tenacity==8.2.3"

      # This installs Chromium **and** the required system packages on the runner.
      - name: Install Playwright browsers + OS deps
        run: |
          python -m playwright install --with-deps chromium

     # --- Potts Point ---
      - name: Run scraper (Potts Point)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          REFERER_URL: "https://laundrlab.com.au/live-status-potts-point/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Potts Point"
        run: |
          python soapranos_potts.py
          tail -n 50 data/soapranos_potts_status.csv || true

      # --- Balmain ---
      - name: Run scraper (Balmain)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=11976"
          REFERER_URL: "https://laundrlab.com.au/live-status-balmain/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Balmain"
        run: |
          python soapranos_balmain.py
          # adjust the CSV path/name inside soapranos_balmain.py if different
          tail -n 50 data/soapranos_balmain_status.csv || true
          
     # --- Bondi ---
      - name: Run scraper (Bondi)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=6190"
          REFERER_URL: "https://laundrlab.com.au/live-status-bondi/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Bondi"
        run: |
          python soapranos_bondi.py
          # adjust the CSV path/name inside soapranos_bondi.py if different
          tail -n 50 data/soapranos_bondi_status.csv || true
