# .github/workflows/laundrlab-potts-scraper.yml
name: laundrlab-scraper-all

on:
  schedule:
    - cron: "2,17,32,47 * * * *"   # every 15 minutes (times are UTC)


permissions:
  contents: read

concurrency:
  group: scrape-laundrlab
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "playwright==1.45.0" "tenacity==8.2.3"
          python -m playwright install --with-deps chromium

     # --- Potts Point ---
      - name: Run scraper (Potts Point)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          REFERER_URL: "https://laundrlab.com.au/live-status-potts-point/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Potts Point"
        run: |
          python laundrlab_potts.py
          tail -n 50 data/laundrlab_potts_status.csv || true

      # --- Balmain ---
      - name: Run scraper (Balmain)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=11976"
          REFERER_URL: "https://laundrlab.com.au/live-status-balmain/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Balmain"
        run: |
          python laundrlab_balmain.py
          # adjust the CSV path/name inside laundrlab_balmain.py if different
          tail -n 50 data/laundrlab_balmain_status.csv || true
          
     # --- Bondi ---
      - name: Run scraper (Bondi)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=6190"
          REFERER_URL: "https://laundrlab.com.au/live-status-bondi/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
          LOCATION: "Bondi"
        run: |
          python laundrlab_bondi.py
          # adjust the CSV path/name inside laundrlab_bondi.py if different
          tail -n 50 data/laundrlab_bondi_status.csv || true
