name: laundrlab-potts-scraper

on:
  schedule:
    - cron: "*/1 * * * *"   # runs every 1 minutes (UTC)
  workflow_dispatch: {}       # allow manual run from the UI

permissions:
  contents: read

concurrency:
  group: scrape-laundrlab
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.45.0 tenacity==8.2.3
          python -m playwright install --with-deps chromium

      - name: Run scraper (posts to Google Sheets)
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          REFERER_URL: "https://laundrlab.com.au/live-status-potts-point/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}  # set this secret
        run: |
          python laundrlab_potts.py
          tail -n 50 data/laundrlab_potts_status.csv || true

      - name: Upload latest CSV (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latest-csv
          path: data/laundrlab_potts_status.csv
          if-no-files-found: ignore
