name: laundrlab-potts-scraper

on:
  # 12:28 and 13:28 UTC daily → covers AEDT (+11) and AEST (+10)
  schedule:
    - cron: "29 12,13 * * *"
  workflow_dispatch: {}   # keep manual trigger as well

permissions:
  contents: read

concurrency:
  group: scrape-laundrlab
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      # Gate: only continue if it's 23:28 in Sydney right now
      - name: Gate by Sydney time (run only at 23:28 Australia/Sydney)
        id: gate
        run: |
          SYD_NOW=$(TZ=Australia/Sydney date +'%H:%M')
          echo "Sydney time is ${SYD_NOW}"
          if [ "$SYD_NOW" = "23:28" ]; then
            echo "RUN=1" >> "$GITHUB_ENV"
          else
            echo "RUN=0" >> "$GITHUB_ENV"
          fi

      - uses: actions/setup-python@v5
        if: env.RUN == '1'
        with:
          python-version: "3.11"

      - name: Print UTC time (debug the schedule)
        if: env.RUN == '1'
        run: |
          echo "UTC time: $(date -u +'%Y-%m-%d %H:%M:%S')"
          echo "Sydney time: $(TZ=Australia/Sydney date +'%Y-%m-%d %H:%M:%S %Z')"

      - name: Install deps
        if: env.RUN == '1'
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.45.0 tenacity==8.2.3
          python -m playwright install --with-deps chromium

      - name: Run scraper
        if: env.RUN == '1'
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          REFERER_URL: "https://laundrlab.com.au/live-status-potts-point/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
        run: |
          python laundrlab_potts.py
          tail -n 50 data/laundrlab_potts_status.csv || true
