name: laundrlab-potts-scraper

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch: {}       # manual run button

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scraper (posts to Google Sheets)
        env:
          # You can hardcode TARGET_URL here or leave it as default in the script
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          # Optional: set via env; the script already includes your URL as a default
          SHEET_WEBAPP_URL: "https://script.google.com/macros/s/AKfycbxSQkRvbFuaiWtxhvgg81S5AzAbCaIlJWRN-XDHT87SC_gH2fGyex1GOZ7pS540hN0W/exec"
        run: |
          python laundrlab_potts.py
          echo "Recent debug CSV (if any):"
          tail -n 20 data/laundrlab_potts_status.csv || true
