name: laundrlab-potts-scraper

on:
  schedule:
    - cron: "*/1 * * * *"   # every 10 minutes (UTC)

permissions:
  contents: read

concurrency:
  group: scrape-laundrlab
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print UTC time (debug the schedule)
        run: date -u

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.45.0 tenacity==8.2.3
          python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          TARGET_URL: "https://wa.sqinsights.com/182471?room=2778"
          REFERER_URL: "https://laundrlab.com.au/live-status-potts-point/"
          SHEET_WEBAPP_URL: ${{ secrets.SHEET_WEBAPP_URL }}
        run: |
          python laundrlab_potts.py
          tail -n 50 data/laundrlab_potts_status.csv || true
